### ISSUE TITLE
'깃허브에서 볼려면 크롬 익스텐션(MathJax Plugin for Github)를 설치해 주세요'

### ISSUE THREAD

**Issue by Kimjio** [tbvjaos510/DGSW-Exam#5]
Only for Chrome?

**Comment by tbvjaos510** [comment]
크롬이나 웨일밖에 아직 못찾은 상태....ㅠ
다른거 찾으면 여기 코멘트 남겨줘요.
그래도 수식은 거의 없어서 없어도 아직은 큰 문제가 없는 상태입니당
